name: example-workflow
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  production-deploy:
    if: GITHUB_WORKFLOW == 'azure-container-webapp.yml'
    runs-on: windows-latest
    steps:
      - run: |
          echo "run successfully"
